apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-rg
  namespace: myapp 
spec:
  selector:
    matchLabels:
      app: tf-rg
  replicas: 1
  template:
    metadata:
      labels:
        app: tf-rg
    spec:
      containers:
      - name: tf-rg
        image: argocdtf.azurecr.io/sampleapp:ce1c9413d8592f057edff11a8cbeb9c3af6ba761
        ports:
        - containerPort: 8080
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "terraform destroy -auto-approve"]

---
apiVersion: v1
kind: Service
metadata:
  name: tf-rg
  namespace: myapp 
spec:
  selector:
    app: tf-rg
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
