apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tfcode
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tfcode
            image: argocdtf.azurecr.io/tfcode:1.0.3
          restartPolicy: Never
          
