apiVersion: v1
kind: Pod
metadata:
  name: tf-code
spec:
  restartPolicy: Never
  containers:
  - name: tf-code
    image: argocdtf.azurecr.io/tfcode:1.0.3
    # Add other container configuration as needed
