kind: Deployment
metadata:
  name: tf-rg
  namespace: myapp 
spec:
  selector:
    matchLabels:
      app: tf-rg
  replicas: 1
  template:
    metadata:
      labels:
        app: tf-rg
    spec:
      containers:
      - name: tf-rg
        image: argocdtf.azurecr.io/tfcode:1.0.3
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: tf-rg
  namespace: myapp 
spec:
  selector:
    app: tf-rg
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
