apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-code
  namespace: myapp 
spec:
  selector:
    matchLabels:
      app: tf-code
  replicas: 1
  template:
    metadata:
      labels:
        app: tf-code
    spec:
      containers:
      - name: tf-code
        image: argocdtf.azurecr.io/tfcode:1.0.8

---
apiVersion: v1
kind: Service
metadata:
  name: tf-code
  namespace: myapp 
spec:
  selector:
    app: tf-code
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
