apiVersion: batch/v1
kind: CronJob
metadata:
  name: tfcode
spec:
  schedule: "@Once"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tfcode
            image: argocdtf.azurecr.io/tfcode:1.0.3
          restartPolicy: Never
          
